name = "college-events"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "college_events_db"
database_id = "cd0747b2-2eee-4052-a172-7d7cf501ed5e" # To be filled after creation
